apiVersion: v1
kind: Secret
metadata:
  name: oba-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.MYSQL_ROOT_PASSWORD | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.MYSQL_PASSWORD | quote }}
  JDBC_PASSWORD: {{ .Values.secrets.JDBC_PASSWORD | quote }}
  GOOGLE_MAPS_API_KEY: {{ .Values.secrets.GOOGLE_MAPS_API_KEY | quote }}
