apiVersion: v1
kind: Service
metadata:
  name: oba-database
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: oba-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
