name: 'CI'

on:
  pull_request:
    branches:
      - main


permissions:
  security-events: write
  contents: read 
  actions: read 

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true
  
jobs:
  opentofu-tests:
    name: 'Opentofu Lint and Tests'
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Opentofu CLI and configure the Opentofu CLI configuration file with a Opentofu Cloud user API token
    - name: Setup Opentofu
      uses: opentofu/setup-opentofu@v1

    # Initialize a new or existing Opentofu working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Opentofu Init
      run: tofu init

    # Validate opentofu files
    - name: Opentofu Validate
      run: tofu validate -no-color

    # Checks that all Opentofu configuration files adhere to a canonical format
    - name: Opentofu Format
      run: tofu fmt -check -recursive
