name: 'Opentofu Lint and Tests'

on:
  push:

permissions:
  security-events: write
  contents: read 
  actions: read 

jobs:
  opentofu-tests:
    name: 'Opentofu Lint and Tests'
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Opentofu CLI and configure the Opentofu CLI configuration file with a Opentofu Cloud user API token
    - name: Setup Opentofu
      uses: opentofu/setup-opentofu@v1

    # Initialize a new or existing Opentofu working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Opentofu Init
      run: opentofu init -backend=false

    # Validate opentofu files
    - name: Opentofu Validate
      run: opentofu validate -no-color

    # Checks that all Opentofu configuration files adhere to a canonical format
    - name: Opentofu Format
      run: opentofu fmt -check -recursive
    
    # Perform a security scan of the opentofu code using checkov
    - name: Run Checkov action
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with: 
        framework: opentofu

    # Upload results to GitHub Advanced Security
    - name: Upload SARIF file
      if: success() || failure()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif
        category: checkov